# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('slug', models.SlugField(null=True)),
                ('cycle', models.CharField(help_text=b'text cycle; even number.', max_length=4, null=True, blank=True)),
                ('is_incumbent', models.BooleanField(default=False, help_text=b'Are they an incumbent? If not, they are a challenger')),
                ('curated_election_year', models.IntegerField(help_text=b"What year is their next election. Set this field--don't overwrite the fec's election year. ", null=True)),
                ('display', models.BooleanField(default=False, help_text=b'Should they be displayed. Use this = False for off cycle candidates.')),
                ('display_name', models.CharField(help_text=b'FEC often has wrong name', max_length=255, null=True)),
                ('not_seeking_reelection', models.BooleanField(default=False, help_text=b'True if they are an incumbent who is not seeking reelection.')),
                ('other_office_sought', models.CharField(help_text=b'E.g. are they running for senate?', max_length=127, null=True, blank=True)),
                ('other_fec_id', models.CharField(help_text=b"If they've declared for another federal position, what is it? This should be the *candidate id* not a committee id. ", max_length=9, null=True, blank=True)),
                ('term_class', models.IntegerField(help_text=b'1,2 or 3. Set this from US Congress repo or soemthing. Only applies to senators.', null=True, blank=True)),
                ('name', models.CharField(help_text=b'name', max_length=255, null=True, blank=True)),
                ('pty', models.CharField(help_text=b'What party?', max_length=3, null=True, blank=True)),
                ('party', models.CharField(help_text=b'Simplified party', max_length=1, null=True, blank=True)),
                ('fec_id', models.CharField(help_text=b'FEC candidate id', max_length=9, null=True, blank=True)),
                ('pcc', models.CharField(help_text=b"FEC id for the candidate's primary campaign committee", max_length=9, null=True, blank=True)),
                ('election_year', models.PositiveIntegerField(help_text=b'Year of general election', null=True, blank=True)),
                ('state', models.CharField(help_text=b'US for president', max_length=2, null=True, blank=True)),
                ('office', models.CharField(max_length=1, null=True, choices=[(b'H', b'House'), (b'S', b'Senate'), (b'P', b'President')])),
                ('office_district', models.CharField(help_text=b"'00' for at-large congress; null for senate, president", max_length=2, null=True, blank=True)),
                ('fec_data_update_time', models.DateTimeField(help_text=b'When was this last set?', null=True, blank=True)),
                ('crp_id', models.CharField(max_length=9, null=True, blank=True)),
                ('transparencydata_id', models.CharField(default=b'', max_length=40, null=True)),
                ('total_expenditures', models.DecimalField(default=0, null=True, max_digits=19, decimal_places=2)),
                ('expenditures_supporting', models.DecimalField(default=0, null=True, max_digits=19, decimal_places=2)),
                ('expenditures_opposing', models.DecimalField(default=0, null=True, max_digits=19, decimal_places=2)),
                ('electioneering', models.DecimalField(default=0, null=True, max_digits=19, decimal_places=2)),
                ('ie_update_time', models.DateTimeField(help_text=b'When were ie totals last updated?', null=True, blank=True)),
                ('total_receipts', models.DecimalField(default=0, null=True, max_digits=19, decimal_places=2)),
                ('total_contributions', models.DecimalField(default=0, null=True, max_digits=19, decimal_places=2)),
                ('total_disbursements', models.DecimalField(default=0, null=True, max_digits=19, decimal_places=2)),
                ('outstanding_loans', models.DecimalField(default=0, null=True, max_digits=19, decimal_places=2, blank=True)),
                ('total_unitemized', models.DecimalField(default=0, null=True, max_digits=19, decimal_places=2)),
                ('cash_on_hand', models.DecimalField(default=0, null=True, max_digits=19, decimal_places=2)),
                ('as_of_date', models.DateField(help_text=b"When are the totals as of? This is slightly dicey because it's theoretically possible that there could be different filing deadlines, but in practice this almost never happens.", null=True)),
                ('candidate_total_update_time', models.DateTimeField(help_text=b'When were candidate totals last updated?', null=True, blank=True)),
                ('is_dirty', models.NullBooleanField(default=True, help_text=b'Do summary numbers need to be recomputed?')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('cycle', models.CharField(max_length=4)),
                ('slug', models.SlugField(max_length=255)),
                ('is_paper_filer', models.NullBooleanField(default=False, help_text=b'True for most senate committees, also NRSC/DSCC, some others.')),
                ('leadership_pac_leader', models.CharField(help_text=b"Leadership pacs are often affiliated with someone who's not a candidate (yet), and maybe never will be. Put their name as text here.", max_length=200, null=True, blank=True)),
                ('org_status', models.CharField(blank=True, max_length=31, null=True, help_text=b"We're only tracking these for non-committees", choices=[(b'501(c)(4)', b'501(c)(4)'), (b'501(c)(5)', b'501(c)(5)'), (b'501(c)(6)', b'501(c)(6)'), (b'527', b'527'), (b'LLC', b'LLC'), (b'Other private business', b'Other private business'), (b'Public business', b'Public business'), (b'Individual', b'individual')])),
                ('political_orientation', models.CharField(help_text=b'The political orientation of the group, as coded by administrators. ', max_length=1, null=True, choices=[(b'R', b'backs Republicans'), (b'D', b'backs Democrats'), (b'U', b'unknown')])),
                ('political_orientation_verified', models.BooleanField(default=False, help_text=b'Check this box if the political orientation has been verified by a human')),
                ('is_dirty', models.NullBooleanField(default=True, help_text=b'Do summary numbers need to be recomputed?')),
                ('name', models.CharField(help_text=b'The committee name.', max_length=255)),
                ('fec_id', models.CharField(help_text=b'The FEC id of the filing committee', max_length=9, blank=True)),
                ('party', models.CharField(max_length=3, null=True, blank=True)),
                ('treasurer', models.CharField(max_length=200, null=True, blank=True)),
                ('street_1', models.CharField(max_length=34, null=True, blank=True)),
                ('street_2', models.CharField(max_length=34, null=True, blank=True)),
                ('city', models.CharField(max_length=30, null=True, blank=True)),
                ('zip_code', models.CharField(max_length=9, null=True, blank=True)),
                ('state', models.CharField(help_text=b'the state where the pac mailing address is', max_length=2, null=True, blank=True)),
                ('connected_org_name', models.CharField(max_length=200, null=True, blank=True)),
                ('filing_frequency', models.CharField(max_length=1, null=True, blank=True)),
                ('candidate_id', models.CharField(max_length=9, null=True, blank=True)),
                ('candidate_office', models.CharField(help_text=b'The office of the candidate that this committee supports. Not all committees support candidates.', max_length=1, null=True, blank=True)),
                ('designation', models.CharField(max_length=1, null=True, choices=[(b'A', b'Authorized by Candidate'), (b'J', b'Joint Fund Raiser'), (b'P', b'Principal Committee of Candidate'), (b'U', b'Unauthorized'), (b'B', b'Lobbyist/Registrant PAC'), (b'D', b'Leadership PAC')])),
                ('ctype', models.CharField(help_text=b'The FEC defined committee type.', max_length=1, null=True, choices=[(b'C', b'Communication Cost'), (b'D', b'Delegate'), (b'E', b'Electioneering Communication'), (b'H', b'House'), (b'I', b'Independent Expenditure (Not a Committee'), (b'N', b'Non-Party, Non-Qualified'), (b'O', b'Super PAC'), (b'P', b'Presidential'), (b'Q', b'Qualified, Non-Party'), (b'S', b'Senate'), (b'U', b'Single candidate independent expenditure'), (b'V', b'PAC with Non-Contribution Account - Nonqualified'), (b'W', b'PAC with Non-Contribution Account - Qualified'), (b'X', b'Non-Qualified Party'), (b'Y', b'Qualified Party'), (b'Z', b'National Party Organization')])),
                ('fec_data_update_time', models.DateTimeField(help_text=b'When was data sourced from FEC about candidate last updated', null=True)),
                ('total_receipts', models.DecimalField(default=0, help_text=b'Total receipts for this committee ceived during the entire cycle. ', null=True, max_digits=19, decimal_places=2)),
                ('total_contributions', models.DecimalField(default=0, null=True, max_digits=19, decimal_places=2)),
                ('total_disbursements', models.DecimalField(default=0, help_text=b'Total disbursements by this committee ceived during the entire cycle', null=True, max_digits=19, decimal_places=2)),
                ('outstanding_loans', models.DecimalField(decimal_places=2, default=0, max_digits=19, blank=True, help_text=b'Total outstanding loans as of the cash_on_hand_date', null=True)),
                ('total_unitemized', models.DecimalField(null=True, max_digits=19, decimal_places=2)),
                ('cash_on_hand', models.DecimalField(default=0, help_text=b"Cash on hand as of the end of committee's most recent periodic report; this date appears as cash_on_hand_date", null=True, max_digits=19, decimal_places=2)),
                ('cash_on_hand_date', models.DateField(help_text=b'The end of the most recent periodic filing; the date that the cash on hand was reported as of.', null=True)),
                ('committee_sum_update_time', models.DateTimeField(help_text=b'When was data sourced from FEC about candidate last updated', null=True)),
                ('has_independent_expenditures', models.NullBooleanField(default=False)),
                ('total_independent_expenditures', models.DecimalField(help_text=b'Total independent expenditures made this cycle.', null=True, max_digits=19, decimal_places=2)),
                ('ie_support_dems', models.DecimalField(default=0, help_text=b'The total amount of independent expenditures make to support Democratic candidates', null=True, max_digits=19, decimal_places=2)),
                ('ie_oppose_dems', models.DecimalField(default=0, help_text=b'The total amount of independent expenditures make to oppose Democratic candidates', null=True, max_digits=19, decimal_places=2)),
                ('ie_support_reps', models.DecimalField(default=0, help_text=b'The total amount of independent expenditures make to support Republican candidates', null=True, max_digits=19, decimal_places=2)),
                ('ie_oppose_reps', models.DecimalField(default=0, help_text=b'The total amount of independent expenditures make to oppose Republican candidates', null=True, max_digits=19, decimal_places=2)),
                ('tot_pres_ind_exp', models.DecimalField(null=True, max_digits=19, decimal_places=2)),
                ('ie_sum_update_time', models.DateTimeField(help_text=b'When was data sourced from FEC about candidate last updated', null=True)),
                ('curated_candidate', models.ForeignKey(related_name='related_candidate', to='efilings.Candidate', help_text=b"For house and senate: Only include if it's a P-primary campaign committee or A-authorized campaign committee with the current cycle as appears in the candidate-committee-linkage file. Check this by hand for presidential candidates though, because many committees claim to be authorized by aren't", null=True)),
                ('leadership_pac_candidate', models.ForeignKey(related_name='leadership_candidate', to='efilings.Candidate', help_text=b'If this is a leadership pac with a candidate affilate, put the candidate here.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('cycle', models.CharField(help_text=b'The even-numbered year that ends a two-year cycle.', max_length=4, null=True, blank=True)),
                ('fec_id', models.CharField(help_text=b'The FEC id of the committee filing this report', max_length=9, null=True, blank=True)),
                ('filing_number', models.CharField(help_text=b'The numeric filing number assigned to this electronic filing by the FEC', max_length=15, unique=True, serialize=False, primary_key=True)),
                ('form_type', models.CharField(help_text=b'The type of form used.', max_length=7, null=True, blank=True)),
                ('filed_date', models.DateField(help_text=b'The date that this filing was processed', null=True, blank=True)),
                ('coverage_from_date', models.DateField(help_text=b'The start of the reporting period that this filing covers. Not all forms list this.', null=True, blank=True)),
                ('coverage_to_date', models.DateField(help_text=b'The end of the reporting period that this filing covers. Not all forms include this', null=True, blank=True)),
                ('process_time', models.DateTimeField(help_text=b'This is the time that FEC processed the filing', null=True, blank=True)),
                ('committee_name', models.CharField(help_text=b"The committee's name as reported to the FEC", max_length=200, null=True, blank=True)),
                ('committee_designation', models.CharField(help_text=b"See the FEC's committee designations", max_length=1, null=True, blank=True)),
                ('committee_type', models.CharField(help_text=b"See the FEC's committee types", max_length=1, null=True, blank=True)),
                ('committee_slug', models.SlugField(max_length=255, null=True, blank=True)),
                ('party', models.CharField(max_length=3, null=True, blank=True)),
                ('filing_is_downloaded', models.CharField(default=b'0', max_length=1)),
                ('header_is_processed', models.CharField(default=b'0', max_length=1)),
                ('previous_amendments_processed', models.CharField(default=b'0', max_length=1)),
                ('new_filing_details_set', models.CharField(default=b'0', max_length=1)),
                ('data_is_processed', models.CharField(default=b'0', max_length=1)),
                ('body_rows_superseded', models.CharField(default=b'0', max_length=1)),
                ('ie_rows_processed', models.CharField(default=b'0', max_length=1)),
                ('filing_error', models.NullBooleanField(default=False)),
                ('filing_error_message', models.TextField(help_text=b'What is the blocking error message', null=True, blank=True)),
                ('coh_start', models.DecimalField(help_text=b'The cash on hand at the start of the reporting period. Not recorded on all forms.', null=True, max_digits=14, decimal_places=2)),
                ('coh_end', models.DecimalField(default=0, help_text=b'The cash on hand at the end of the reporting period. ', null=True, max_digits=14, decimal_places=2)),
                ('new_loans', models.DecimalField(default=0, help_text=b'The amount of new loans taken on by the committee during this reporting period.', null=True, max_digits=14, decimal_places=2)),
                ('tot_raised', models.DecimalField(default=0, help_text=b'The total amount raised in this report. This is total receipts for periodic reports.', null=True, max_digits=14, decimal_places=2)),
                ('tot_spent', models.DecimalField(default=0, help_text=b'The total amount spent in this report.', null=True, max_digits=14, decimal_places=2)),
                ('tot_ies', models.DecimalField(default=0, help_text=b'The total amount of independent expenditures ', null=True, max_digits=14, decimal_places=2)),
                ('tot_coordinated', models.DecimalField(default=0, null=True, max_digits=14, decimal_places=2)),
                ('is_amendment', models.BooleanField()),
                ('amends_filing', models.IntegerField(null=True, blank=True)),
                ('amendment_number', models.IntegerField(null=True, blank=True)),
                ('superseded_by_amendment', models.BooleanField(default=False, help_text=b'Is this filing superseded by another filing, either a later amendment, or a periodic filing')),
                ('amended_by', models.IntegerField(null=True, blank=True)),
                ('covered_by_periodic_filing', models.BooleanField(default=False)),
                ('covered_by', models.IntegerField(null=True, blank=True)),
                ('is_f5_quarterly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OtherLine',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('line_number', models.IntegerField()),
                ('filing_number', models.CharField(max_length=15)),
                ('superseded_by_amendment', models.BooleanField(default=False)),
                ('form_parser', models.CharField(max_length=6, blank=True)),
                ('form_type', models.CharField(max_length=8, blank=True)),
                ('filer_committee_id_number', models.CharField(max_length=9, null=True, blank=True)),
                ('transaction_id', models.CharField(max_length=20, null=True, blank=True)),
                ('line_data', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkedA',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('line_number', models.IntegerField()),
                ('filing_number', models.CharField(max_length=15)),
                ('superseded_by_amendment', models.BooleanField(default=False)),
                ('form_type', models.CharField(max_length=8, blank=True)),
                ('filer_committee_id_number', models.CharField(max_length=9, null=True, blank=True)),
                ('transaction_id', models.CharField(max_length=20, null=True, blank=True)),
                ('back_reference_tran_id_number', models.CharField(max_length=20, null=True, blank=True)),
                ('back_reference_sched_name', models.CharField(max_length=8, null=True, blank=True)),
                ('entity_type', models.CharField(help_text=b'[CAN|CCM|COM|IND|ORG|PAC|PTY]', max_length=3, null=True, blank=True)),
                ('contributor_name', models.CharField(help_text=b'deprecated as a field since v5.3', max_length=200, null=True, blank=True)),
                ('contributor_organization_name', models.CharField(max_length=200, null=True, blank=True)),
                ('contributor_last_name', models.CharField(max_length=30, null=True, blank=True)),
                ('contributor_first_name', models.CharField(max_length=20, null=True, blank=True)),
                ('contributor_middle_name', models.CharField(max_length=20, null=True, blank=True)),
                ('contributor_prefix', models.CharField(max_length=10, null=True, blank=True)),
                ('contributor_suffix', models.CharField(max_length=10, null=True, blank=True)),
                ('contributor_street_1', models.CharField(max_length=34, null=True, blank=True)),
                ('contributor_street_2', models.CharField(max_length=34, null=True, blank=True)),
                ('contributor_city', models.CharField(max_length=30, null=True, blank=True)),
                ('contributor_state', models.CharField(max_length=2, null=True, blank=True)),
                ('contributor_zip', models.CharField(max_length=9, null=True, blank=True)),
                ('election_code', models.CharField(max_length=5, null=True, blank=True)),
                ('election_other_description', models.CharField(help_text=b"required if election code starts with 'O' for other", max_length=20, null=True, blank=True)),
                ('contribution_date', models.CharField(help_text=b'exactly as it appears', max_length=8, null=True, blank=True)),
                ('contribution_date_formatted', models.DateField(help_text=b'Populated from parsing raw field', null=True)),
                ('contribution_amount', models.DecimalField(null=True, max_digits=14, decimal_places=2)),
                ('contribution_aggregate', models.DecimalField(null=True, max_digits=14, decimal_places=2)),
                ('contribution_purpose_code', models.CharField(help_text=b'deprecated', max_length=3, null=True, blank=True)),
                ('contribution_purpose_descrip', models.CharField(max_length=100, null=True, blank=True)),
                ('contributor_employer', models.CharField(max_length=38, null=True, blank=True)),
                ('contributor_occupation', models.CharField(max_length=38, null=True, blank=True)),
                ('donor_committee_fec_id', models.CharField(max_length=9, null=True, blank=True)),
                ('donor_committee_name', models.CharField(max_length=200, null=True, blank=True)),
                ('donor_candidate_fec_id', models.CharField(max_length=9, null=True, blank=True)),
                ('donor_candidate_name', models.CharField(help_text=b'deprecated', max_length=200, null=True, blank=True)),
                ('donor_candidate_last_name', models.CharField(max_length=30, null=True, blank=True)),
                ('donor_candidate_first_name', models.CharField(max_length=20, null=True, blank=True)),
                ('donor_candidate_middle_name', models.CharField(max_length=20, null=True, blank=True)),
                ('donor_candidate_prefix', models.CharField(max_length=10, null=True, blank=True)),
                ('donor_candidate_suffix', models.CharField(max_length=10, null=True, blank=True)),
                ('donor_candidate_office', models.CharField(max_length=1, null=True, blank=True)),
                ('donor_candidate_state', models.CharField(max_length=2, null=True, blank=True)),
                ('donor_candidate_district', models.CharField(max_length=2, null=True, blank=True)),
                ('conduit_name', models.CharField(max_length=200, null=True, blank=True)),
                ('conduit_street1', models.CharField(max_length=34, null=True, blank=True)),
                ('conduit_street2', models.CharField(max_length=34, null=True, blank=True)),
                ('conduit_city', models.CharField(max_length=30, null=True, blank=True)),
                ('conduit_state', models.CharField(max_length=2, null=True, blank=True)),
                ('conduit_zip', models.CharField(max_length=9, null=True, blank=True)),
                ('memo_code', models.CharField(max_length=1, null=True, blank=True)),
                ('memo_text_description', models.CharField(max_length=100, null=True, blank=True)),
                ('reference_code', models.CharField(max_length=9, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkedB',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('line_number', models.IntegerField()),
                ('filing_number', models.CharField(max_length=15)),
                ('superseded_by_amendment', models.BooleanField(default=False)),
                ('form_type', models.CharField(max_length=8, blank=True)),
                ('filer_committee_id_number', models.CharField(max_length=9, null=True, blank=True)),
                ('transaction_id', models.CharField(max_length=20, null=True, blank=True)),
                ('back_reference_tran_id_number', models.CharField(max_length=20, null=True, blank=True)),
                ('back_reference_sched_name', models.CharField(max_length=8, null=True, blank=True)),
                ('entity_type', models.CharField(help_text=b'[CAN|CCM|COM|IND|ORG|PAC|PTY]', max_length=3, null=True, blank=True)),
                ('payee_name', models.CharField(help_text=b'deprecated', max_length=100, null=True, blank=True)),
                ('payee_organization_name', models.CharField(max_length=200, null=True, blank=True)),
                ('payee_last_name', models.CharField(max_length=30, null=True, blank=True)),
                ('payee_first_name', models.CharField(max_length=20, null=True, blank=True)),
                ('payee_middle_name', models.CharField(max_length=20, null=True, blank=True)),
                ('payee_prefix', models.CharField(max_length=10, null=True, blank=True)),
                ('payee_suffix', models.CharField(max_length=10, null=True, blank=True)),
                ('payee_street_1', models.CharField(max_length=34, null=True, blank=True)),
                ('payee_street_2', models.CharField(max_length=34, null=True, blank=True)),
                ('payee_city', models.CharField(max_length=30, null=True, blank=True)),
                ('payee_state', models.CharField(max_length=2, null=True, blank=True)),
                ('payee_zip', models.CharField(max_length=9, null=True, blank=True)),
                ('election_code', models.CharField(max_length=5, null=True, blank=True)),
                ('election_other_description', models.CharField(help_text=b"required if election code starts with 'O' for other", max_length=20, null=True, blank=True)),
                ('expenditure_date', models.CharField(help_text=b'exactly as it appears', max_length=8, null=True, blank=True)),
                ('expenditure_date_formatted', models.DateField(help_text=b'Populated from parsing raw field', null=True)),
                ('expenditure_amount', models.DecimalField(null=True, max_digits=14, decimal_places=2)),
                ('semi_annual_refunded_bundled_amt', models.DecimalField(help_text=b'Used for F3L only', null=True, max_digits=14, decimal_places=2)),
                ('expenditure_purpose_code', models.CharField(help_text=b'deprecated', max_length=3, null=True, blank=True)),
                ('expenditure_purpose_descrip', models.CharField(max_length=100, null=True, blank=True)),
                ('category_code', models.CharField(max_length=3, null=True, blank=True)),
                ('beneficiary_committee_fec_id', models.CharField(max_length=9, null=True, blank=True)),
                ('beneficiary_committee_name', models.CharField(max_length=200, null=True, blank=True)),
                ('beneficiary_candidate_fec_id', models.CharField(max_length=9, null=True, blank=True)),
                ('beneficiary_candidate_name', models.CharField(help_text=b'deprecated', max_length=100, null=True, blank=True)),
                ('beneficiary_candidate_last_name', models.CharField(max_length=30, null=True, blank=True)),
                ('beneficiary_candidate_first_name', models.CharField(max_length=20, null=True, blank=True)),
                ('beneficiary_candidate_middle_name', models.CharField(max_length=20, null=True, blank=True)),
                ('beneficiary_candidate_prefix', models.CharField(max_length=10, null=True, blank=True)),
                ('beneficiary_candidate_suffix', models.CharField(max_length=10, null=True, blank=True)),
                ('beneficiary_candidate_office', models.CharField(max_length=1, null=True, blank=True)),
                ('beneficiary_candidate_state', models.CharField(max_length=2, null=True, blank=True)),
                ('beneficiary_candidate_district', models.CharField(max_length=2, null=True, blank=True)),
                ('conduit_name', models.CharField(max_length=200, null=True, blank=True)),
                ('conduit_street_1', models.CharField(max_length=34, null=True, blank=True)),
                ('conduit_street_2', models.CharField(max_length=34, null=True, blank=True)),
                ('conduit_city', models.CharField(max_length=30, null=True, blank=True)),
                ('conduit_state', models.CharField(max_length=2, null=True, blank=True)),
                ('conduit_zip', models.CharField(max_length=9, null=True, blank=True)),
                ('memo_code', models.CharField(max_length=1, null=True, blank=True)),
                ('memo_text_description', models.CharField(max_length=100, null=True, blank=True)),
                ('ref_to_sys_code_ids_acct', models.CharField(max_length=9, null=True, blank=True)),
                ('refund_or_disposal_of_excess', models.CharField(help_text=b'deprecated', max_length=20, null=True, blank=True)),
                ('communication_date', models.CharField(help_text=b'deprecated', max_length=9, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkedE',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('line_number', models.IntegerField()),
                ('filing_number', models.CharField(max_length=15)),
                ('superseded_by_amendment', models.BooleanField(default=False)),
                ('effective_date', models.DateField(help_text=b"What date should we use? Through version 8.0 of FECfile, there was only an 'expenditure date', but beginning with v8.1 there were two dates--a dissemination date and an expenditure date. For v8.1 use the dissemination date; for earlier version use the expenditure date.", null=True)),
                ('form_type', models.CharField(max_length=8, blank=True)),
                ('filer_committee_id_number', models.CharField(max_length=9, null=True, blank=True)),
                ('transaction_id', models.CharField(help_text=b'The transaction id from the original filing. These ids are unique per report, not necessarily per cycle.', max_length=20, null=True, blank=True)),
                ('back_reference_tran_id_number', models.CharField(max_length=20, null=True, blank=True)),
                ('back_reference_sched_name', models.CharField(max_length=8, null=True, blank=True)),
                ('entity_type', models.CharField(help_text=b'[CAN|CCM|COM|IND|ORG|PAC|PTY]', max_length=3, null=True, blank=True)),
                ('payee_name', models.CharField(help_text=b'deprecated', max_length=100, null=True, blank=True)),
                ('payee_organization_name', models.CharField(help_text=b'The name of the organization being paid', max_length=200, null=True, blank=True)),
                ('payee_last_name', models.CharField(max_length=30, null=True, blank=True)),
                ('payee_first_name', models.CharField(max_length=20, null=True, blank=True)),
                ('payee_middle_name', models.CharField(max_length=20, null=True, blank=True)),
                ('payee_prefix', models.CharField(max_length=10, null=True, blank=True)),
                ('payee_suffix', models.CharField(max_length=10, null=True, blank=True)),
                ('payee_street_1', models.CharField(help_text=b'The street address of the payee', max_length=34, null=True, blank=True)),
                ('payee_street_2', models.CharField(help_text=b'The street address of the payee -- second part, if needed.', max_length=34, null=True, blank=True)),
                ('payee_city', models.CharField(help_text=b"The payee's city", max_length=30, null=True, blank=True)),
                ('payee_state', models.CharField(help_text=b'Payee state', max_length=2, null=True, blank=True)),
                ('payee_zip', models.CharField(help_text=b'Payee ZIP code', max_length=9, null=True, blank=True)),
                ('election_code', models.CharField(help_text=b'The code describing the election', max_length=5, null=True, blank=True)),
                ('election_other_description', models.CharField(help_text=b'Any additional description of the election', max_length=20, null=True, blank=True)),
                ('expenditure_date', models.CharField(max_length=8, null=True, blank=True)),
                ('expenditure_date_formatted', models.DateField(help_text=b'The date of the expenditure', null=True)),
                ('dissemination_date', models.CharField(help_text=b'The dissemination date, only in v8.1 and higher.', max_length=8, null=True, blank=True)),
                ('dissemination_date_formatted', models.DateField(help_text=b'The dissemination date, only in v8.1 and higher.', null=True)),
                ('expenditure_amount', models.DecimalField(help_text=b'The expenditure amount', null=True, max_digits=14, decimal_places=2)),
                ('calendar_y_t_d_per_election_office', models.DecimalField(null=True, max_digits=14, decimal_places=2)),
                ('expenditure_purpose_code', models.CharField(help_text=b"The filer-entered code of the expenditure. This isn't required.", max_length=3, null=True, blank=True)),
                ('expenditure_purpose_descrip', models.CharField(help_text=b'The filer-described purpose of the expenditure', max_length=100, null=True, blank=True)),
                ('category_code', models.CharField(max_length=3, null=True, blank=True)),
                ('payee_cmtte_fec_id_number', models.CharField(max_length=9, null=True, blank=True)),
                ('support_oppose_code', models.CharField(max_length=1, null=True, blank=True)),
                ('candidate_id_number', models.CharField(max_length=9, null=True, blank=True)),
                ('candidate_name', models.CharField(help_text=b'deprecated', max_length=100, null=True, blank=True)),
                ('candidate_last_name', models.CharField(max_length=30, null=True, blank=True)),
                ('candidate_first_name', models.CharField(max_length=20, null=True, blank=True)),
                ('candidate_middle_name', models.CharField(max_length=20, null=True, blank=True)),
                ('candidate_prefix', models.CharField(max_length=10, null=True, blank=True)),
                ('candidate_suffix', models.CharField(max_length=10, null=True, blank=True)),
                ('candidate_office', models.CharField(max_length=1, null=True, blank=True)),
                ('candidate_state', models.CharField(max_length=2, null=True, blank=True)),
                ('candidate_district', models.CharField(max_length=2, null=True, blank=True)),
                ('completing_last_name', models.CharField(max_length=30, null=True, blank=True)),
                ('completing_first_name', models.CharField(max_length=20, null=True, blank=True)),
                ('completing_middle_name', models.CharField(max_length=20, null=True, blank=True)),
                ('completing_prefix', models.CharField(max_length=10, null=True, blank=True)),
                ('completing_suffix', models.CharField(max_length=10, null=True, blank=True)),
                ('date_signed', models.CharField(max_length=8, null=True, blank=True)),
                ('date_signed_formatted', models.DateField(help_text=b'Populated from parsing raw field', null=True)),
                ('memo_code', models.CharField(help_text=b'This is an X for lines that are subitemizations', max_length=1, null=True, blank=True)),
                ('memo_text_description', models.CharField(help_text=b'A text description of unique circumstances surrounding this expenditure.', max_length=100, null=True, blank=True)),
                ('candidate_targeted', models.ForeignKey(to='efilings.Candidate', help_text=b'The candidate targeted by this independent expenditure.', null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together=set([('fec_id', 'cycle')]),
        ),
        migrations.AlterUniqueTogether(
            name='committee',
            unique_together=set([('cycle', 'fec_id')]),
        ),
    ]
